title: Shortcut Assistant
logo: /assets/img/assistant.png
description: "Streamline your Shortcut project management analyze stories, track deadlines with emojis, and keeping private notes for ultimate efficiency."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
