title: Shortcut Assistant
logo: /assets/img/assistant.png
description: "Streamline your Shortcut project management analyze stories, track work, and keep private notes for ultimate efficiency."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
