# Theme Configuration
theme: jekyll-theme-minimal

# Site settings
title: Shortcut Assistant
description: A brief description of your site
baseurl: "" # the subpath of your site, e.g., /blog
url: "" # the base hostname & protocol for your site, e.g., http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Optional settings
google_analytics: YOUR_GOOGLE_ANALYTICS_TRACKING_ID # if you want to track analytics
show_downloads: true # if you want to show a download button for your repository
