title: Shortcut Assistant
logo: /assets/img/assistant.png
description: "Streamline your Shortcut project management: analyze stories w/ AI, track stalled work with emojis, and keep private notes for ultimate efficiency."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
package_version: 0.6