name: Auto Reviewer

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  review-pr:
    runs-on: ubuntu-latest
    name: Review Pull Request

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Generate git diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff FETCH_HEAD..HEAD > diff.txt

      - name: Install dependencies
        run: cd reviewer && npm install

      - name: Run script and capture output
        id: run_script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
        run: |
          output="$(node ./reviewer/review.js)"
          echo "comment=$output" >> $GITHUB_OUTPUT

      - name: Post comment to PR
        uses: actions/github-script@v4
        env:
          COMMENT: ${{ steps.run_script.outputs.comment }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const comment = process.env.COMMENT;
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: comment,
            })
