name: Auto Reviewer

on:
  pull_request:
    types: [ opened, synchronize ]


jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Review Pull Request
        uses: "JensAstrup/ai-reviewer@v1.0.1"
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
