name: Auto Reviewer

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Review Pull Request
        uses: "JensAstrup/auto-reviewer@main"
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
