name: Auto Reviewer

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  review:
    uses: JensAstrup/auto-reviewer/.github/workflows/main-workflow.yml@main
    with:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
