name: Prepare Release Assets

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

env:
  NODE_ENV: production

jobs:
  prepare-release-assets:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.draft_release.outputs.upload_url }}
      release_id: ${{ steps.draft_release.outputs.release_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install all dependencies
        env:
          NODE_ENV: development
        run: cd src && yarn

      - name: Extract tag name
        id: extract_tag
        run: echo "VERSION=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Add API_SECRET and VERSION to .env
        run: |
          echo VERSION=${{ github.event.pull_request.title }} >> .env
          echo GOOGLE_ANALYTICS_API_SECRET=${{ secrets.GOOGLE_ANALYTICS_API_SECRET }} >> .env

      - name: Build extension
        env:
          NODE_ENV: development
          VERSION: ${{ env.VERSION }}
        run: |
          mkdir dist
          cd src
          yarn run manifest
          yarn run build-css

      - name: Build extension
        run: |
          cd src
          yarn run build
        env:
          SENTRY_RELEASE: "shortcut-assistant@${{ env.VERSION }}"
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VERSION: ${{ env.VERSION }}

      - name: Zip extension
        run: |
          cd src
          rm -rf node_modules
          yarn install --production
          yarn run dist
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VERSION: ${{ env.VERSION }}
          SENTRY_RELEASE: "shortcut-assistant@${{ env.VERSION }}"

      - name: Upload dist.zip as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-zip
          path: dist/dist.zip

      - name: Create or update draft release
        id: draft_release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./.github/scripts/create-or-update-draft-release.js');
            script({ github, context, core });
