name: Run Linter

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --immutable
        
      - name: Run ESLint on changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          config_path: "eslint.config.mjs"
          token: ${{ secrets.GITHUB_TOKEN }}
