name: Run Linter

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch changes
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21.x
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Get list of changed files
        id: files
        run: echo "::set-output name=files::$(git diff --name-only origin/${{ github.base_ref }}..${{ github.head_ref }} | xargs)"
      - name: Run linter on changed files
        run: echo ${{ steps.files.outputs.files }} | xargs npm run lint
