name: Run Linter

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21.x
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Get changed files
        id: changed-files
        run: |
          BASE_BRANCH=$(jq -r '.pull_request.base.ref' "$GITHUB_EVENT_PATH")
          git fetch origin $BASE_BRANCH
          git checkout $BASE_BRANCH
          git checkout -b temp-branch
          git merge $GITHUB_REF --no-commit --no-ff
          git diff --name-only HEAD | grep -E '\.(js|ts|tsx)$' > changed_files.txt
      - name: Run linter
        run: |
          if [ -s changed_files.txt ]; then
            xargs npm run lint -- < changed_files.txt
          else
            echo "No JavaScript or TypeScript files changed"
          fi
