name: Comment and Fail on PR from Non-Version Branches

on:
  pull_request:
    branches:
      - main
    types: [opened, edited]

jobs:
  comment-and-fail-on-non-v-branch:
    if: startsWith(github.event.pull_request.head.ref, 'V') == false && startsWith(github.event.pull_request.head.ref, 'v') == false
    runs-on: ubuntu-latest
    steps:

      - name: Leave comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "🚨 Only version branches are allowed to be merged into the main branch."
          delete-branch: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail checks
        run: |
          echo "Failing the check because the branch name does not start with 'V' or 'v'."
          exit 1
