name: Publish Release

on:
  workflow_run:
    workflows: ["Release Version"]
    types:
      - completed

# Define minimum required permissions
permissions:
  contents: write    # Needed for updating releases
  actions: read      # Needed to download artifacts

jobs:
  publish-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_branch != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: dist-zip
          path: dist

      - name: Get PR information
        id: pr_info
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const getMergedPrInfo = require('./.github/scripts/get-merged-pr-info.js');
            return await getMergedPrInfo({ github, context, core });

      - name: Update and publish release
        if: steps.pr_info.outputs.pr_title
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const updateAndPublishRelease = require('./.github/scripts/update-and-publish-release.js');
            await updateAndPublishRelease({ 
              github, 
              context, 
              core, 
              releaseTag: '${{ steps.pr_info.outputs.pr_title }}',
              releaseBody: '${{ steps.pr_info.outputs.pr_body }}'
            });
