name: Auto Reviewer

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Review Pull Request
        uses: "JensAstrup/ai-reviewer@air-2-refactor-code"
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
